/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IAntDesignSettingFilled: typeof import('~icons/ant-design/setting-filled')['default']
    ICarbonSendFilled: typeof import('~icons/carbon/send-filled')['default']
    ICharmChevronLeft: typeof import('~icons/charm/chevron-left')['default']
    ICharmChevronRight: typeof import('~icons/charm/chevron-right')['default']
    ILogosBing: typeof import('~icons/logos/bing')['default']
    IMingcuteMenuFill: typeof import('~icons/mingcute/menu-fill')['default']
    IPepiconsPopRefresh: typeof import('~icons/pepicons-pop/refresh')['default']
    IRiOpenaiFill: typeof import('~icons/ri/openai-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
